backend:
  name: git-gateway
  branch: master
  squash_merges: true
local_backend: true
publish_mode: editorial_workflow
media_library:
  name: cloudinary
  config:
    cloud_name: kisi-kloud
    api_key: 289736137856832
media_folder: 'static/images/uploads'
public_folder: '/images/uploads'
collections:
  - name: 'blog' # Used in routes, e.g., /admin/collections/blog
    label: 'Blog' # Used in the UI
    label_singular: 'Blog Article'
    folder: '_posts/blog' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    sortable_fields: ['title', 'summary', 'rating', 'date']
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Summary', name: 'summary ', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image' }
      - { label: 'Rating (scale of 1-5)', name: 'rating', widget: 'number' }
      - {
          label: 'Author',
          name: 'author',
          widget: 'relation',
          collection: 'authors',
          search_fields: ['name', 'job'],
          value_field: 'name',
          display_fields: ['name', 'job'],
        }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'authors' # Used in routes, e.g., /admin/collections/blog
    label: 'Authos' # Used in the UI
    label_singular: 'Author'
    folder: '_posts/authors' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: 'name'
    sortable_fields: ['name', 'job', 'date']
    fields: # The fields for each document, usually in front matter
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Job Title', name: 'job', widget: 'string' }
      - { label: 'Image', name: 'img', widget: 'image' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
  - name: 'categories' # Used in routes, e.g., /admin/collections/blog
    label: 'Categories' # Used in the UI
    label_singular: 'Category'
    folder: '_posts/categories' # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{slug}}' # Filename template, e.g., YYYY-MM-DD-title.md
    identifier_field: 'name'
    sortable_fields: ['name', 'summary', 'date']
    fields: # The fields for each document, usually in front matter
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
